### ISSUE TITLE
01 unit tests fails when using generators (Python3)

### ISSUE THREAD

**Issue by ryoung29** [pybites/challenges#1]
I'm pretty sure I have the right answer, but my functions return generators, not list/tuples. You should probably coerce an iterator in the test or else give instructions about what you expect in the tests in the README.

**Comment by pybites** [comment]
Do you have your solution to reproduce it? Challenge 01 right? Thanks

**Comment by richyvk** [comment]
My Challenge 1 also fails your tests but it works. Rather my solution raises an error running your test: I get ```TypeError: expected str, bytes or os.PathLike object, not tuple``` using ```open(dict_file) as f:``` in my load_words function. You can see my code here: https://github.com/richyvk/challenges/blob/master/01/wordvalue.py

It's probably something I've done wrong!

**Comment by bbelderbos** [comment]
Problem seems the default arg of max_word_value: 

def max_word_value(words=DICTIONARY):
    ....

If you set it up as in our solution: 
https://github.com/pybites/challenges/blob/solutions/01/wordvalue.py

Like so: 

def max_word_value(words=None):
   ...
    """
    if words:
        words_list = words
    else:
        words_list = load_words()

It works:
Ran 3 tests in 0.828s
OK

HTH

**Comment by richyvk** [comment]
Thanks. I see now what I did wrong!
