### ISSUE TITLE
docs correction to code challenge 02

### ISSUE THREAD

**Issue by netserf** [pybites/challenges#153]
Hi Folk

I'm not sure if you have a repo for taking pull requests on your pybit.es site docs, but I noticed an issue with this challenge - https://pybit.es/codechallenge02.html

> Use one of the templates:
> `$ cd 02`
> `$ cp game-TEMPLATE.py game.py`

There is no `game-TEMPLATE.py` file in the repo. I think you mean `game-help.py`  or `game-nohelp.py`.

If you have a repo somewhere for this I can make the updates and submit the PR.

Cheers!

**Comment by pybites** [comment]
Hey Greg, yep for challenges this is the right repo and yes, it referred to one of these files. 

I can change it but we do have an official way now to correct the blog:

- go to post, in this case https://pybit.es/codechallenge02.html
- scroll to bottom where it says "See an error in this post? Please submit a pull request on Github."
- follow that link (points to https://github.com/pybites/pybites.github.io-src) 
- PR your change there

Thanks!
