### ISSUE TITLE
Python Queues solutions

### ISSUE THREAD

**Issue by jvidin** [pybites/challenges#175]
Build a chalenge on the light of this [Medium Post](https://medium.com/@ssola/playing-with-twitter-streaming-api-b1f8912e50b0) - with producing and consuming from Queues.
Could be fun taking the example of Twitter streaming API and RabbitMQ like the post mentions.

**Comment by pybob81** [comment]
Awesome thanks, this is a cool example. We use this to track pybites Twitter mentions but not with RabbitMQ. Definitely on our todo list, maybe adding Celery to this challenge too ...

**Comment by bbelderbos** [comment]
That was me ;)

**Comment by juanAzpiroz** [comment]
I'm begining using PyBites, so now just looking

**Comment by bbelderbos** [comment]
are you on our Slack? this would be a cool one for a new blog challenge ...

**Comment by pybites** [comment]
@jvidin something like this? https://pybit.es/codechallenge50.html - or you wanted something else?

**Comment by jvidin** [comment]
That looks great , thanks @pybites @bbelderbos  you never forget a good chanlenge. :-)

**Comment by pybites** [comment]
Still need to solve it (lol) but we have it in so closing this issue.
