### ISSUE TITLE
Challange 04 test fails due to non-static data

### ISSUE THREAD

**Issue by alexjaw** [pybites/challenges#220]
At this moment the required text for the last tweet appears instead already at item 97.
A solution is to mock the tweepy.API and inject static tweets. Will also dramatically decrease the test time (3s > 0.01s).

**Comment by pybites** [comment]
I learned this skill > this challenge. I was just gonna give this a go (done it by now) but stumbled upon your PR (sorry, we have been busy), thanks a lot, will check verify and merge it now!

**Comment by pybites** [comment]
Fixed recently
