### ISSUE TITLE
Challenge 04: techmoneykids is no longer a valid twitter handle

### ISSUE THREAD

**Issue by bmiraski** [pybites/challenges#255]
The challenge no longer will work with techmoneykids because it is not a valid twitter handle. 

Easy to work around, but could be a shock to those who haven't seen the error before.

**Comment by pybites** [comment]
I updated Julian's Twitter handle for PCC04 but the tests would run regardless, did you use these? https://github.com/pybites/challenges/blob/solutions/04/test_usertweets.py

**Comment by bmiraski** [comment]
Yes, the tests ran no matter the items in the actual code. Just used to fail while actually building the code and checking to make sure that the main function ran properly.

**Comment by bbelderbos** [comment]
OK thanks for checking
