### ISSUE TITLE
Peer Code Review

### ISSUE THREAD

**Issue by mridubhatnagar** [pybites/challenges#277]
1. Try reading and understanding someone else's code.
2. Mention about the goods.
3. Suggest if you have a more pythonic way of doing the same.
4. Discuss feature extension if one has any idea.

**Comment by bbelderbos** [comment]
Cool, this could even be a feature on the platform :)
We already have a bite forum feature ...

**Comment by bbelderbos** [comment]
This can be done on any PR and on Slack. It might also turn into a feature on our platform over time. Thanks
