### ISSUE TITLE
make a pybites url shortener?

### ISSUE THREAD

**Issue by bbelderbos** [pybites/challenges#339]
https://impythonist.wordpress.com/2015/10/31/building-your-own-url-shortening-service-with-python-and-flask/

**Comment by bbelderbos** [comment]
Cool, I have not solved it yet, but think it will be a good learning experience!

**Comment by bbelderbos** [comment]
Closing this by accident but did so correctly as we already wrote up a PCC for this: https://codechalleng.es/challenges/61/

**Comment by clamytoe** [comment]
Just created PR for this: [bitesofpy_contrib#26](https://github.com/pybites/bitesofpy_contrib/pull/26)

**Comment by clamytoe** [comment]
Well... I guess my tab didn't update because I just now saw that you had closed it when I posted that message.
