### ISSUE TITLE
It would be great to have some challenges with PRAW API.

### ISSUE THREAD

**Issue by shibasisp** [pybites/challenges#42]

**Comment by pybites** [comment]
Thanks, sounds interesting. What problem would you like to solve with that API? Examples welcome

**Comment by shibasisp** [comment]
I haven't thought much about it yet. However here are two ideas from my side.
* A program that would fetch one challenge from easy, one from Intermediate and one hard from [r/dailyprogrammer](https://www.reddit.com/r/dailyprogrammer/) and shows it in the console.
* A program that would fetch 10(or so) news from [r/news](https://www.reddit.com/r/news/) and sort it in decreasing order of upvotes.

**Comment by pybites** [comment]
These will be perfect for a challenge. I specially like the first one. We will schedule it in. 
Thanks!

Best regards,
Bob

**Comment by bbelderbos** [comment]
Hey @shibasisp - this turned into this week's challenge: https://pybit.es/codechallenge27.html - thanks, looking forward seeing your submission.

**Comment by shibasisp** [comment]
Thanks @bbelderbos . From this week, I will try to complete most of your challenges.

**Comment by pybites** [comment]
Cool, you want to join our private Slack as well where we discuss challenges, Python and more?

**Comment by shibasisp** [comment]
Sure!! I would love to.. 😄

**Comment by pybites** [comment]
OK sent you an invite
