### ISSUE TITLE
PR shows all previously changed files and previous commits

### ISSUE THREAD

**Issue by abkosar** [pybites/challenges#553]
When I try to follow the git setup on <https://codechalleng.es/challenges/52/> and try to create a PR, it shows all the previously changed files and previous commits instead of just 1.

Any help will be appreciated, thanks!

**Comment by bbelderbos** [comment]
Hey @abkosar seems you tried to merge into master, that needs to be community. The platform should provide a link that pre-selects community as the target merge branch, did it not? 
I reopened your PR and fixed it manually for now, it works: I only see your code now.
HTH
Bob

**Comment by abkosar** [comment]
Hey @bbelderbos, thanks for the advice. Yeah I didn't pay attention to that.

Thanks!
