### ISSUE TITLE
PCC02 Problem related to dictionary path (Maybe related to Windows)

### ISSUE THREAD

**Issue by userinfamous** [pybites/challenges#599]
This problem can be resolved by copying the dict file from PCC01 into PCC02 instead of rerouting it to be ```../01/dictionary.txt```.
So basically it doesn't get the file filled with words but just the path, it reads that as the word. Thus failing the Assert check for the length of the wordlist.

**Comment by clamytoe** [comment]
If working locally, are you maintaining the same directory structure? If you are and the file exists, how are you loading the file? 

The bites are generally designed to work on the platform, when working locally things like this will show up once in a while. For instance, there are challenges that use the /tmp directory to download files to and that directory does not exist in Windows. 

A work around would be to remove the / and create a tmp directory where your script is. Same with this but, just copy the file to where your script is and modify the path. 

Troubleshooting things like this will make you a better developer in the long run. Just make sure to change it back before submitting. 

In this case, duplicating the file would be an easy fix, but won’t help you in the later challenges that I mentioned.

**Comment by userinfamous** [comment]
I'm not sure about the later problems but for pcc01 and pcc02, there's a need to add sys.path.append('..') for me to be able to actually get files beyond the top level of the parent directory. I'm not sure about Linux but all that is well and fine but the path in the text file isn't redirected to the pcc01 path as I mentioned above, it simply looks at it as a line of text and read it, adding it to the list after splitting.

**Comment by clamytoe** [comment]
I was going to copy it over for you. Just getting ready to head into the office though, so it’ll be a while.

**Comment by clamytoe** [comment]
I've taken a look at the challenge repo and the `dictionary.txt` file is already in there. Are you talking about your solution? Seems that you didn't move the source files into your own directory to work on, so yeah, this is a non-issue and you were correct to close it.

**Comment by userinfamous** [comment]
Thanks, the reason you didn't see it before is probably because I haven't pushed anything onto the community branch yet.
