### ISSUE TITLE
challenge around refactoring code

### ISSUE THREAD

**Issue by bbelderbos** [pybites/challenges#66]
- recent article on this topic
- community members reviewing each other's code (wow)
- important developer skill

- could make it a requirement to add tests before refactoring :)

**Comment by pybites** [comment]
On that last note: 
http://blog.thedigitalcatonline.com/blog/2017/07/21/refactoring-with-test-in-python-a-practical-example/#.WXUnvtOGPeQ

**Comment by pybites** [comment]
done == PCC30
