### ISSUE TITLE
AWS Lambda Challenge

### ISSUE THREAD

**Issue by mjhea0** [pybites/challenges#77]
Write an AWS Lamda function that calls https://github.com/realpython/web-dev-for-data-scientists/blob/master/exercises/flask-bitcoin/data.py every hour and updates the chart in https://pybit.es/codechallenge28.html.

**Comment by viveksyngh** [comment]
I want to work on this one.

**Comment by pybites** [comment]
Cool, PR your solution :)

**Comment by pybites** [comment]
So the challenge is live, so you can refer to https://pybit.es/codechallenge36.html - closing this issue.
