### ISSUE TITLE
Create a cookiecutter template challenge. 

### ISSUE THREAD

**Issue by clamytoe** [pybites/challenges#81]
The challenge would be to create your own cookiecutter template for creating a file or "project" files that you always create when starting a new project in order to cut down on boilerplate code.

**Comment by pybites** [comment]
cool, I really need to try this tool!

**Comment by clamytoe** [comment]
I created my toepack cookiecutter template, which has been a great success for me. I love that thing!

**Comment by bbelderbos** [comment]
Awesome man, everybody reading this give @clamytoe's toepack some love: https://github.com/clamytoe/toepack
