### ISSUE TITLE
Slack Link not working?

### ISSUE THREAD

**Issue by soumyas567** [pybites/challenges#827]
Hi, 
Found this repository through my suggestions. Tried to join the slack community. But the link given in Readme.md is not working. Is this still happening and maintained?

**Comment by bbelderbos** [comment]
Hey @soumyas567 thanks for the heads up, it's https://pybit.es/community/ these days (we made it a page because Slack invalidates these links, so we have a single source of truth). I updated the README.

Cu there :)

Cheers,
Bob

**Comment by soumyas567** [comment]
> Hey @soumyas567 thanks for the heads up, it's https://pybit.es/community/ these days (we made it a page because Slack invalidates these links, so we have a single source of truth). I updated the README.
> 
> Cu there :)
> 
> Cheers,
> Bob

Thanks. I did👍
