### ISSUE TITLE
Regex challenge part 2

### ISSUE THREAD

**Issue by pybites** [pybites/challenges#96]
Could deliver unittests of matches and ask the dev to write regexes to pass the tests

**Comment by pybites** [comment]
https://regexly.chipto.io/

**Comment by exepaul** [comment]
Here are some interesting challenges which i solved on stackoverflow : 

This program use double regex trick : 
https://dpaste.de/6fZm

Convert 5A2B4C11G string to [(5,“A”),(2,“B”),(4,“C”),(11,“G”)] in Python
I tried this problem with regex here : 
https://stackoverflow.com/a/46511015/5904928

simple ip checker regex problem : 
https://stackoverflow.com/a/46642321/5904928

more regex problem : 
https://stackoverflow.com/a/46761376/5904928
https://stackoverflow.com/questions/46547514/delete-first-3-characters-of-string-in-python/46547635#46547635

Negative look ahead regex : 
https://stackoverflow.com/a/46726116/5904928

Replace with regex : 
https://stackoverflow.com/a/46747234/5904928

**Comment by bbelderbos** [comment]
Nice. Tomorrow is a new month so let’s do some regex too. Thanks for your inputs.

**Comment by pybites** [comment]
Part 1 done (PCC42), leaving this one open for a potential part 2 using links above

**Comment by mridubhatnagar** [comment]
Another good link on advance regex.
http://www.rexegg.com/regex-disambiguation.html#lookarounds

**Comment by bbelderbos** [comment]
Mostly implemented as Bites
